Домашнее задание №1
unn3daby/2024-2-VK-EDU-Frontend-I-MARCHENKO pull request #2
Opened 2024-09-17 21:39 UTC by unn3daby

# Домашнее задание №1

Прошу @martinkomitsky, @haseprogram, @kgrechin или @nelkor.

Что было сделано:
* Задачку с предложением
* Задачку с байтами + пару тестов
* Задачку с неуникальными элементами (хотел как-то без двух переборов, но как понял это нереально) 

PS  Очень пытался решить байты с помощью побитовых операторов (ради интереса исключительно) , но столкнулся с сложностью получения остатка, поэтому забил и сделал на логарифмах

2024-09-18 15:31 UTC, nelkor requested changes
Пока что поревьюил только функцию `convertBytesToHuman`. Прошу учесть комментарии и внести необходимые изменения во все файлы.

2024-09-18 15:31 UTC, nelkor commented on lesson_1/convertBytesToHuman.js
> +  if (isNaN(bytes) || typeof bytes !== 'number' || bytes < 0) return false;
Во-первых, вместо проверок `typeof`и `isNaN` достаточно одной проверки [isFinite](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/isFinite).

Во-вторых, здесь функция возвращает `false`, хотя в условии задачи сказано, что функция должна возвращать строку. Если в условии не сказано, что функция должна возвращать что-то особенное в случае ошибки, то я рекомендую [выбрасывать исключение](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw).

Соответственно, в тестах будет проверка на [toThrow](https://jestjs.io/ru/docs/expect#tothrowerror).

**ЗАЧЁРКНУТО**

В тестах написаны "примеры" кейсов, и там `=== false`, значит оставляем так, как там требуется.

2024-09-18 15:31 UTC, nelkor commented on lesson_1/convertBytesToHuman.js
> +  const value = (bytes / 1024**sizeIndex);
По стилю кода, любой (не унарный) арифметический оператор отделяется пробелами с обоих сторон. Возможно, здесь отсутствие пробелов вызвано желанием явно выполнить возведение в степень вперёд деления. Впрочем, по [приоритету операторов](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Operator_precedence), возведение в степень и так выше.

```suggestion
  const value = (bytes / 1024 ** sizeIndex);
```

2024-09-18 15:31 UTC, nelkor commented on lesson_1/convertBytesToHuman.js
> +  const formattedValue = Number.isInteger(value) ? value.toString() : value.toFixed(2);
Это приводит к появлению таких строк, как "1.50 GB" (вместо "1.5 GB"). Попробуй придумать, как избавиться от завершающего нуля у подобных дробных чисел.

2024-09-18 15:31 UTC, nelkor commented on lesson_1/convertBytesToHuman.js
> +}
Как написал в чате, файлы должны заканчиваться пустой строкой.

2024-09-18 15:31 UTC, nelkor commented on .gitignore
> +dist
Прошу также добавить сюда `package-lock.json`, чтобы не было пяти тысяч строк изменений.

2024-09-19 13:08 UTC, nelkor submitted a review, later dismissed
Очень классное элегантное решение с логарифмами. Трим строки тоже порадовал. Ну и ещё классно, что выбрасываешь исключения и проверяешь их в тесте.

2024-09-19 13:10 UTC, unn3daby commented
> Очень классное элегантное решение с логарифмами. Трим строки тоже порадовал. Ну и ещё классно, что выбрасываешь исключения и проверяешь их в тесте.

Спасибо! Ну про исключения ты писал в телеге, поэтому это не совсем моя инициатива)

2024-09-19 13:22 UTC, nelkor submitted a review, later dismissed

2024-09-19 13:27 UTC, martinkomitsky submitted a review, later dismissed

2024-09-19 13:29 UTC, martinkomitsky approved these changes

2024-09-19 13:30 UTC, nelkor submitted a review, later dismissed

2024-09-19 15:13 UTC, kgrechin approved these changes

2024-09-19 15:14 UTC, nelkor approved these changes

2024-09-19 15:16 UTC, kgrechin commented
@HaseProgram, @martinkomitsky 2 апррува есть

2024-09-21 16:58 UTC, martinkomitsky approved these changes
Поддержу коллег, крутое решение!
12!

2024-09-21 16:58 UTC, merged