Second homework
unn3daby/2024-2-VK-EDU-Frontend-I-MARCHENKO pull request #3
Opened 2024-09-25 20:41 UTC by unn3daby

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @nelkor.

Что было сделано:
*
*
*

2024-09-26 08:00 UTC, nelkor requested changes
JS-файлы должны быть названы в kebab-case, за исключение файлов-классов, которые называют в PascalCase.

В целом, решение хорошее. Но на маленьких экранах выглядит плохо, нужна адаптивность.

2024-09-26 08:04 UTC, unn3daby commented on simple-chat/src/public/index.html
> +          ></div>
с textarea куча проблем была со стилям.  Я глянул, в телеге как раз этот способ используется.

2024-09-26 08:16 UTC, unn3daby commented on simple-chat/src/public/index.html
> +          ></div>
![5451850289918371235](https://github.com/user-attachments/assets/585c47a5-8ef8-4fb2-ab61-a0b32c3ff424)

2024-09-27 09:40 UTC, nelkor commented on simple-chat/src/public/index.html
> +          ></div>
Напиши подробнее, что за проблемы со стилями. По хорошему, надо сделать `textarea`, но если будут невероятно сложные проблемы, то можно будет сделать, как в Телеграме)

2024-09-27 15:18 UTC, unn3daby commented on simple-chat/src/public/index.html
> +          ></div>
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/99481218-3ee6-46ee-a729-aa4455bbf396">
Не получилось центрировать поле для ввода

2024-09-27 15:20 UTC, unn3daby commented on simple-chat/src/public/index.html
> +          ></div>
также для textarea придется писать скрипт, чтобы она ресайзилась по вертикали при переносе строки

2024-09-27 15:29 UTC, unn3daby commented on simple-chat/src/public/index.html
> +          ></div>
Тк в задании не было ничего про ресайз, я конечно могу вставить textarea, тупо задать высоту и все(((
если честно не очень хочется, хоть это и проще

2024-10-02 12:30 UTC, nelkor commented on simple-chat/src/public/index.html
> +          ></div>
Использовать в качестве textarea div — это плохая практика. Пока что я не вижу ультимативных причин делать это.

2024-10-02 12:33 UTC, nelkor requested changes
Код выглядит хорошо, но нет ссылки на развёрнутое приложение. И надо всё-таки исправить textarea.

2024-10-02 12:33 UTC, nelkor commented on simple-chat/package.json
> +    "build": "webpack --mode=development"
Для сборки нужен мод production.

2024-10-02 12:34 UTC, unn3daby commented on simple-chat/src/public/index.html
> +          ></div>
ок, верну textarea

2024-10-02 12:50 UTC, unn3daby commented on simple-chat/package.json
> +    "build": "webpack --mode=development"
https://unn3daby.github.io/2024-2-VK-EDU-Frontend-I-MARCHENKO/ - еще сюда продублирую на всякий

2024-10-03 14:22 UTC, nelkor approved these changes

2024-10-03 18:12 UTC, HaseProgram approved these changes
12!

2024-10-03 18:12 UTC, merged